import Config

# Configure your database
# Use environment variables if available, otherwise use defaults
config :embedding_generator, EmbeddingGenerator.Repo,
  username: System.get_env("DO_DB_USERNAME") || "postgres",
  password: System.get_env("DO_DB_PASSWORD") || "postgres",
  hostname: System.get_env("DO_DB_HOSTNAME") || "localhost",
  port: String.to_integer(System.get_env("DO_DB_PORT") || "5432"),
  database: System.get_env("DO_DB_NAME") || "embedding_generator_dev",
  ssl: System.get_env("DO_DB_SSL_CERT") != nil,
  ssl_opts:
    if(System.get_env("DO_DB_SSL_CERT"),
      do: [cacertfile: System.get_env("DO_DB_SSL_CERT")],
      else: []
    ),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Digital Ocean Spaces configuration (if environment variables are set)
if System.get_env("SPACES_ACCESS_KEY_ID") do
  config :ex_aws,
    access_key_id: System.get_env("SPACES_ACCESS_KEY_ID"),
    secret_access_key: System.get_env("SPACES_SECRET_ACCESS_KEY")

  config :ex_aws, :s3,
    scheme: "https://",
    host: "#{System.get_env("BUCKET_NAME")}.nyc3.digitaloceanspaces.com",
    region: "nyc3"
end

# Oban configuration - always enabled for development
config :embedding_generator, Oban, queues: [embeddings: 10], plugins: [Oban.Plugins.Pruner]

# Allow batch size to be configured via environment variable
if batch_size = System.get_env("EMBEDDING_BATCH_SIZE") do
  config :embedding_generator, EmbeddingGenerator.BatchProcessor,
    batch_size: String.to_integer(batch_size)
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :embedding_generator, EmbeddingGeneratorWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "8yajWi4B8exfHsbA50Ue+2G/viEFP6JcYWWyRHMTXU1JD42x7nm9Q8c4gCmJxy4L",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:embedding_generator, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:embedding_generator, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :embedding_generator, EmbeddingGeneratorWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/embedding_generator_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :embedding_generator, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
